# Generated by Django 4.0.5 on 2022-06-13 08:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(default=None, max_length=255, unique=True)),
                ('category_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='Not Posted', max_length=255)),
                ('item_price', models.SmallIntegerField()),
                ('item_image', models.ImageField(upload_to='')),
                ('old_price', models.SmallIntegerField()),
                ('quantity_type', models.CharField(choices=[('Cup', 'Cup'), ('Plate', 'Plate'), ('Piece', 'Piece'), ('Glass', 'Glass')], default='Plate', max_length=255)),
                ('item_category', models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='food.menucategory')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('GUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('table_number', models.CharField(max_length=2)),
                ('is_occupied', models.BinaryField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField(default=1)),
                ('order_state', models.CharField(choices=[('Ordered', 'Ordered'), ('Dispatched', 'Cooking'), ('Cooking', 'Dispatched')], default='ordered', max_length=15)),
                ('item_id', models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.menuitems')),
                ('table_id', models.ForeignKey(default=django.db.models.deletion.SET_NULL, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.table')),
            ],
        ),
    ]
